version = 1

[[rule]]
name = "收盘高于开盘"
scope_windows = 1
scope_way = "LAST"
when = "C > O"
points = 10.0
explain = "当天阳线给分"
tag = "Opportunity"

[[rule]]
name = "3日内上涨次数"
scope_windows = 3
scope_way = "EACH"
when = "C > REF(C,1)"
points = 2.0
explain = "最近3天每次上涨加2分"
tag = "Opportunity"
